`ActiveFederationID` field added in FedimintClient
Kodylow/fedimint-sdk-go pull request #2
Opened 2024-03-10 05:38 UTC by PsychoPunkSage

Added the missing `ActiveFederationID` field in `FedimintClient` and made some changes in `main.go` to use `ActiveFederationID`...
I also tried to eliminate some warnings in some of the structs by explicitly providing each elements their own types

2024-03-10 17:59 UTC, Kodylow approved these changes
The active federation id needs to be used for any of the federation specific endpoints , see fedimint-ts for example:

https://github.com/Kodylow/fedimint-ts/blob/2e3d85ab15c52de6f494426edcf2dc22154c96cf/FedimintClient.ts#L155C2-L169C4

You have to check in `fedimint-http`'s endpoints or just copy fedimint-ts for reference for which ones use it. It's pretty much all the module specific endpoints.

2024-03-10 17:59 UTC, Kodylow commented on cmd/main.go
> +	activeFederationId := os.Getenv("ACTIVE_FEDITIONAL_ID")
FEDERATION_ID

2024-03-10 17:59 UTC, Kodylow commented on cmd/main.go
> +		activeFederationId = "activeFederationId"
should use better defaults

2024-03-10 17:59 UTC, Kodylow commented on pkg/fedimint/client.go
>  }
This looks wrong, I'm pretty sure this should be a byte array?

2024-03-10 18:00 UTC, Kodylow requested changes
sorry, hit approve instead of request changes, see prev comments

2024-03-10 18:58 UTC, PsychoPunkSage commented on pkg/fedimint/client.go
>  }
Ah,
In Typescript it is given as 
```typescript
interface FederationIdPrefix {
    0: number; // Assuming u8 is equivalent to number in TypeScript
    1: number;
    2: number;
    3: number;
}
```
I don't think this is using bytes...

2024-03-10 18:58 UTC, PsychoPunkSage commented on cmd/main.go
> +		activeFederationId = "activeFederationId"
Ok Sure,
How about `defaultId`?

2024-03-10 18:59 UTC, PsychoPunkSage commented on cmd/main.go
> +	activeFederationId := os.Getenv("ACTIVE_FEDITIONAL_ID")
Ah,
You mean I should replace `activeFederationId` with `FEDERATION_ID` (in upper_case), right?

2024-03-10 19:14 UTC, Kodylow commented on pkg/fedimint/client.go
>  }
it comes in as a bytearray from the rust but that typescript reads them into numbers, Go you should maintain them as a bytearray

2024-03-11 17:19 UTC, PsychoPunkSage commented on pkg/fedimint/client.go
>  }
Ok I will make necessary Changes

2024-03-11 17:55 UTC, PsychoPunkSage commented
I have made necessary changes.
Should I create a new PR or is there any way to merge my changes in this PR?

2024-03-11 19:41 UTC, merged